SELECT LTYRDNBR AS YARD, LTLOTNBR AS LOT, LTFLG2UD AS VATFLAG, LBHIBID AS HIBID, (LBSLRCRG - LBACGTOT) AS SELLFEE, (LBCPGREV + LBTOWFEE) AS PROGREV, 0.00 AS OTHERREV, STSTLDES AS TITLE, LTSLRNBR AS SELLER
FROM GBRPRDDB.LOTLT
JOIN GBRPRDDB.LOTBILLB ON
LTLOTNBR = LBLOTNBR
JOIN GBRPRDDB.SELLERSO ON
LTSLRNBR = SOSLRNBR
JOIN GBRPRDDB.CASHSTST ON
LTLOTNBR = STLOT#
WHERE ((LBINVCCC * 1000000) + (LBINVYYY * 10000) + (LBINVMMM * 100) + (LBINVDDD)) BETWEEN StartDate AND EndDate AND
LBCPGCAT <> 'PPP' AND
LTACLTYP = ' ' AND
LTYRDNBR NOT IN (451, 452, 470, 471, 475, 480)
ORDER BY LTYRDNBR, LTLOTNBR