SELECT LPLOTNBR AS LOT, SOSLRNBR AS SELLER, LPTRPTYP AS TYPE, LPDRVTYP AS DRIVERTYPE, LPTRPZON AS TRIPZONE, LPCOMERN AS COMMISSION
FROM GBRPRDDB.LOTTRPLP
JOIN GBRPRDDB.LOTLT ON
LTLOTNBR = LPLOTNBR
JOIN GBRPRDDB.LOTBILLB ON
LBLOTNBR = LTLOTNBR
JOIN GBRPRDDB.SELLERSO ON
SOSLRNBR = LTSLRNBR
WHERE ((LBINVCCC * 1000000) + (LBINVYYY * 10000) + (LBINVMMM * 100) + (LBINVDDD)) BETWEEN StartDate AND EndDate AND
SOSLRNBR LIKE 'CD%' AND
LTACLTYP = ' ' 